gui:
  border: single
  commandLogSize: 12
  # expandFocusedSidePanel: true
  mainPanelSplitMode: flexible
  nerdFontsVersion: "3"
  # screenMode: full
  sidePanelWidth: 0.5
  showBottomLine: true
  showDivergenceFromBaseBranch: arrowAndNumber
  showCommandLog: true
  showFileIcons: true
  showRandomTip: false
  statusPanelView: allBranchesLog
  theme:
    selectedLineBgColor:
      - underline
notARepository: skip
